# Generated by Django 5.0.6 on 2024-06-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blog_alter_comment_blog_alter_like_blog_delete_blogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
